# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ad0eb0fd5948585f43ee4073af05c396bad2eb1796a8a5eac7aa49b7296288d7ea8a8a4ec53f55415862d07df14b2f3633ef911b85be1c34366e9acd91002d

test:
  secret_key_base: d2ff29b4cee87c74a8a6100602217c118a1eab61731fa37ca80855aa44a51e1ff7229d597f4de4c354ce126a1e4ac0b02878c4a11fc5f1171725c4734506f642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
